# Generated by Django 2.2.3 on 2024-02-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactanos',
            name='mail',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
